name: upgrade_tool
description: Used to resolve warnings caused by `xxxbinding. Instance` in Flutter 3.0
version: 1.0.5

homepage: https://github.com/fluttercandies/upgrade_tool


environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  process_run: ^0.12.3+2

dev_dependencies:
  lints: ^1.0.0

